### ISSUE TITLE
sharpcap crashes when selecting the Lumix camera (S1)

### ISSUE THREAD

**Issue by davidenitti** [totoantibes/LumixCameraAscomDriver#4]
I have a panasonic S1, when I select the ascom Lumix on sharpcap I have this error:
```
CheckDotNetExceptions ASCOM.Lumix.Camera ImageArray Get System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at ASCOM.Lumix.Camera.get_ImageArray() (See Inner Exception for details)
```
![Screenshot 2021-03-20 185740](https://user-images.githubusercontent.com/7438184/111881029-f30d9300-89ae-11eb-8884-cb42726e9179.png)

**Comment by totoantibes** [comment]
i dont have the S1 so hard for me to reproduce. however:

1. are you sure you have the latest version of my driver? I changed the imagearray method at some point to be compatible with Nina. So maybe this is to do with that.
2. what happens if you try to connect in "thumb" mode in the ASCOM driver? there is another issue with the S1 where i may have the sensor size wrong. Will try to fix that however if you connect in JG or RAW then the imagearray maybe wrong size and create this erroe
3. Not that it should matter but are you running sharpcap 64 bt or 32 bit?

I have not been using sharpcap really as it is better suited for video/liveview cameras. When I connect my lumix it is emulating a liveview by taking constant shots. do you experience the same behaviour? The only exception i have seen so far is if i take too short exposure once connected then the driver does not have the time to get the image on the PC and i have a "file not found" exception.

**Comment by colharris113** [comment]
Hello, I have a GX880 and am experiencing the same issue with Sharpcap - it connects, but bails out when it takes its first picture.  I've tried Thumb mode and a few other settings, nothing helps.  Idenfies as a GF10.

Ascom diagnostics seems to connect ok  Temporary folder exists and there's images in there.

CheckDotNetExceptions ASCOM.Lumix.Camera ImageArray Get System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at ASCOM.Lumix.Camera.get_ImageArray() (See Inner Exception for details)

**Comment by davidenitti** [comment]
did you find a solution?

**Comment by colharris113** [comment]
No, hence the post

**Comment by davidenitti** [comment]
any update on this?

**Comment by totoantibes** [comment]
i did a fresh test this am with sharpcap 4.0 64 bits and my lumix gh5s. it works rather well. either in " live view"  or still mode.
please try with latest release of driver.
also make sure that all settings in driver are correct especially the resolution as well as the destination folder for the temp file. if is is a "system" type folder then app will not have access to read/write to it. best is use your "documents" folder as a temp.

**Comment by davidenitti** [comment]
when I check the properties it says that there are no cameras. so it doesn't find it.

**Comment by totoantibes** [comment]
so in that case here is the fool proof method: 
1) pair your camera on your home wifi
2) connect to it with your phone app
3) take 1 pic from your phone
4) find the ip of the camera on your home wifi
5) go in ascom profile explorer and enter manually the ip of the camera in it
6) start nina/apt
7) look for settings on ascom camera in nina
8) it should discover the camera.
9)  click ok/connect
10) go to sharpcap....

**Comment by davidenitti** [comment]
not sure if I can connect to my home wifi. I have to check this

with the camera wifi I know for sure the IP, in any case the diagnostics gives this when I connect

Create              Creating device
Connected           Connecting to device
                    
Name                Lumix Ascom Driver
Description         Lumix Camera
DriverInfo          Lumix Wifi Ascom driver. Version: 7.0
DriverVersion       7.0
InterfaceVersion    2
CameraXSize         6026
CameraYSize         4017
BinX                1
BinY                1
MaxBinX             1
MaxBinY             1
HasShutter          True
                    
Connected           Disconnecting from device
Dispose             Disposing of device
Dispose             Completed disposal
ReleaseComObject    Releasing COM instance
GC Collect          Starting garbage collection
GC Collect          Completed garbage collection
